In [1]:
import pandas as pd 
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
df_train = pd.read_hdf('../data/processed/train/aggr_train_zeros.hdf')
df_train.head()

,ID,shop_id,item_id,year,month,item_name,item_category_id,item_category_name,first_big_category,last_big_category,...,count_last_week_mall_first_big_category,count_last_week_mall_last_big_category,count_last_week_city_item_id,count_last_week_city_item_category_id,count_last_week_city_first_big_category,count_last_week_city_last_big_category,fridays,days_in_a_month,expected_sales,item_cnt_day
0,0,5,5037,2014,10,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,Игры,PS3,...,165.0,25.0,0.0,25.0,165.0,25.0,5,31,0.000000,0.0
1,2,5,5233,2014,10,"Need for Speed Rivals (Essentials) [PS3, русск...",19,Игры - PS3,Игры,PS3,...,165.0,25.0,0.0,25.0,165.0,25.0,5,31,0.000000,0.0
2,15,5,4872,2014,10,"Minecraft. Playstation 3 Edition [PS3, русская...",19,Игры - PS3,Игры,PS3,...,165.0,25.0,1.0,25.0,165.0,25.0,5,31,4.428571,3.0
3,21,5,5002,2014,10,"NBA 2K16 [PS3, русская документация]",19,Игры - PS3,Игры,PS3,...,165.0,25.0,0.0,25.0,165.0,25.0,5,31,0.000000,0.0
4,23,5,5814,2014,10,"Plants vs. Zombies Garden Warfare [PS3, русска...",19,Игры - PS3,Игры,PS3,...,165.0,25.0,1.0,25.0,165.0,25.0,5,31,4.428571,2.0

In [2]:
df_test = pd.read_hdf('../data/processed/test/aggr_test.hdf')
df_test.head(10)

,ID,shop_id,item_id,year,month,item_name,item_category_id,item_category_name,first_big_category,last_big_category,...,count_last_week_mall_item_category_id,count_last_week_mall_first_big_category,count_last_week_mall_last_big_category,count_last_week_city_item_id,count_last_week_city_item_category_id,count_last_week_city_first_big_category,count_last_week_city_last_big_category,fridays,days_in_a_month,expected_sales
0,0,5,5037,2015,11,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000
1,2,5,5233,2015,11,"Need for Speed Rivals (Essentials) [PS3, русск...",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000
2,15,5,4872,2015,11,"Minecraft. Playstation 3 Edition [PS3, русская...",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,2.0,14.0,82.0,14.0,3,30,8.571429
3,21,5,5002,2015,11,"NBA 2K16 [PS3, русская документация]",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000
4,23,5,5814,2015,11,"Plants vs. Zombies Garden Warfare [PS3, русска...",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,1.0,14.0,82.0,14.0,3,30,4.285714
5,56,5,3341,2015,11,"FIFA 15 [PS3, русская версия]",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000
6,58,5,3350,2015,11,"FIFA 16 [PS3, русская версия]",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000
7,62,5,3365,2015,11,"FIFA Street (Essentials) [PS3, английская версия]",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000
8,69,5,3686,2015,11,"God of War 3 (Essentials) [PS3, русская версия]",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000
9,81,5,3444,2015,11,"Far Cry 4 [PS3, русская версия]",19,Игры - PS3,Игры,PS3,...,14.0,82.0,14.0,0.0,14.0,82.0,14.0,3,30,0.000000

In [3]:
df_train['date'] = pd.to_datetime(df_train['year'].astype(str) + '-' + df_train['month'].astype(str) + '-1')
df_train['date'].max()

Timestamp('2015-10-01 00:00:00')

In [3]:
df_total = df_train 
df_total['train'] = 1
df_test['train'] = 0 
df_total = pd.concat([df_train, df_test], copy=False)
df_total.head()

,ID,aggr_from_date,aggr_to_date,city,count_aggr_1_month_ago_city,count_aggr_1_month_ago_city_first_big_category,count_aggr_1_month_ago_city_item_category_id,count_aggr_1_month_ago_city_item_id,count_aggr_1_month_ago_city_last_big_category,count_aggr_1_month_ago_first_big_category,...,item_cnt_day,item_id,item_name,last_big_category,mall,month,shop_id,shop_name,train,year
0,0,2014-04-01,2014-10-01,Вологда,1536.0,616.0,131.0,0.0,139.0,38586.0,...,0.0,5037,"NHL 15 [PS3, русские субтитры]",PS3,Мармелад,10,5,"Вологда ТРЦ ""Мармелад""",1,2014
1,2,2014-04-01,2014-10-01,Вологда,1536.0,616.0,131.0,0.0,139.0,38586.0,...,0.0,5233,"Need for Speed Rivals (Essentials) [PS3, русск...",PS3,Мармелад,10,5,"Вологда ТРЦ ""Мармелад""",1,2014
2,15,2014-04-01,2014-10-01,Вологда,1536.0,616.0,131.0,6.0,139.0,38586.0,...,3.0,4872,"Minecraft. Playstation 3 Edition [PS3, русская...",PS3,Мармелад,10,5,"Вологда ТРЦ ""Мармелад""",1,2014
3,21,2014-04-01,2014-10-01,Вологда,1536.0,616.0,131.0,0.0,139.0,38586.0,...,0.0,5002,"NBA 2K16 [PS3, русская документация]",PS3,Мармелад,10,5,"Вологда ТРЦ ""Мармелад""",1,2014
4,23,2014-04-01,2014-10-01,Вологда,1536.0,616.0,131.0,2.0,139.0,38586.0,...,2.0,5814,"Plants vs. Zombies Garden Warfare [PS3, русска...",PS3,Мармелад,10,5,"Вологда ТРЦ ""Мармелад""",1,2014

In [4]:
dim_red = pd.read_hdf('../data/processed/total_pca.hdf', 'pca')

In [5]:
df_total[dim_red.columns] = dim_red

In [8]:
df_train = df_total[df_total['train'] == 1]
df_test = df_total[df_total['train'] == 0]

In [10]:
df_train[['ID'] + ['pca_' + str(i) for i in range(4)]].to_hdf('../data/processed/train/pca.hdf', 'pca')
df_test[['ID'] + ['pca_' + str(i) for i in range(4)]].to_hdf('../data/processed/test/pca.hdf', 'pca')

In [5]:
df_total_cnt = df_total[[col for col in df_total.columns if col.startswith('count')]]

In [6]:
df_total_cnt.to_hdf('../data/processed/total_cnt.hdf', 'total')

In [1]:
import pandas as pd 
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
df_total_cnt = pd.read_hdf('../data/processed/total_cnt.hdf')

In [15]:
del df_train
del df_test

In [6]:
t = PCA(n_components=0.95)
df_total_transf = t.fit_transform(df_total_cnt)

In [5]:
df_total_transf.shape

(2998800, 3)

In [7]:
df_total_transf.shape

(2998800, 4)

In [9]:
dim_red = pd.DataFrame(df_total_transf, columns=['pca_' + str(i) for i in range(4)])
dim_red.head()

          pca_0          pca_1         pca_2         pca_3
0 -35840.121448 -311164.411766 -19230.753314 -45744.622350
1 -35840.146211 -311164.281054 -19230.841393 -45744.618013
2 -35839.950060 -311165.302030 -19230.138928 -45744.653964
3 -35840.146211 -311164.281055 -19230.841393 -45744.618013
4 -35840.124500 -311164.388240 -19230.768880 -45744.620433

In [10]:
dim_red.to_hdf('../data/processed/total_pca.hdf', 'pca')