In [1]:
from datetime import datetime
import pandas as pd 
df = pd.read_hdf('../data/processed/train/aggr_train.hdf')
df_valid = pd.read_hdf('../data/processed/validation/aggr_valid.hdf')

threshold = datetime(2015, 10, 1)

df_train = df[df['date'] < threshold]
df_valid_y_data = df[df['date'] == threshold][['shop_id', 'item_id', 'item_cnt_day']]

df_valid = pd.merge(
    df_valid, df_valid_y_data,
    on=['shop_id', 'item_id'],
    how='left'
    ).fillna(0)

In [4]:
(df_valid['item_cnt_day'] == 0).mean()

0.8663211951447246

In [5]:
df_valid['count_aggr_1_month_ago_shop_id_item_id']

,ID,shop_id,item_id,year,month,item_name,item_category_id,item_category_name,big_category,date,...,count_aggr_year_shop_id_item_category_id,count_aggr_6_months_shop_id_item_category_id,count_aggr_2_quartals_ago_shop_id_item_category_id,count_aggr_3_months_shop_id_big_category,count_aggr_1_month_shop_id_big_category,count_aggr_1_month_ago_shop_id_big_category,count_aggr_year_shop_id_big_category,count_aggr_6_months_shop_id_big_category,count_aggr_2_quartals_ago_shop_id_big_category,item_cnt_day
0,0,5,5037,2015,10,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,Игры,2015-10-01,...,1039.0,503.0,242.0,1315.0,456.0,524.0,5668.0,2505.0,1269.0,0.0
1,5100,4,5037,2015,10,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,Игры,2015-10-01,...,706.0,305.0,158.0,1011.0,284.0,407.0,5637.0,2183.0,1352.0,0.0
2,10200,6,5037,2015,10,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,Игры,2015-10-01,...,1099.0,394.0,249.0,1704.0,700.0,550.0,9733.0,3881.0,2167.0,1.0
3,15300,3,5037,2015,10,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,Игры,2015-10-01,...,876.0,350.0,230.0,1013.0,419.0,299.0,4868.0,2114.0,1181.0,0.0
4,20400,2,5037,2015,10,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,Игры,2015-10-01,...,1324.0,519.0,276.0,1525.0,500.0,597.0,6844.0,2963.0,1460.0,0.0

SyntaxError: invalid syntax (<ipython-input-6-321e6921d584>, line 1)

In [ ]:
LogReg no one hots
RMSE:  1.1531126957907112
LogReg hots
RMSE:  1.0835073359890597
Previous
RMSE:  1.134420305900261
RF 6
RMSE:  1.0249088757806013
RF 8
RMSE: 1
RF 9 
RMSE: 1
RF 9 z kolumnami
RMSE: 1